services:
  - type: web
    name: mern-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false        
      - key: JWT_SECRET
        sync: false       
      - key: CLIENT_URL
        value: https://mern-frontend.onrender.com   

  - type: web
    name: mern-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://mern-backend.onrender.com   
